live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#867462"
blue = "#A3A9CE"
cyan = "#89B3B6"
green = "#85B695"
magenta = "#CF9BC2"
red = "#D47766"
white = "#ECE1D7"
yellow = "#EBC06D"

[colors.normal]
black = "#34302C"
blue = "#7F91B2"
cyan = "#7B9695"
green = "#78997A"
magenta = "#B380B0"
red = "#BD8183"
white = "#C1A78E"
yellow = "#E49B5D"

[colors.primary]
background = "#292522"
foreground = "#ECE1D7"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[debug]
log_level = "Warn"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "Iosevka NF"
style = "Bold"

[font.normal]
family = "Iosevka NF"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[scrolling]
history = 25000

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.98
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 36

[window.padding]
x = 5
y = 5
